AAVSO/VStar

plugin/src/org/aavso/tools/vstar/external/plugin/KeplerFITSObservationSource.java

Added constructor as per Max's proposal. Appears to work correctly now.

#12: added constructor which passes VeLa filter string to base class

---

src/org/aavso/tools/vstar/ui/pane/list/ObservationListPane.java

So I finally got around to testing the git mechanics.  After some problems I decided to do all work from command line git.  
Let me know if this looks ok.

Just added a comment to test git mechanics

---

src/org/aavso/tools/vstar/plugin/period/PeriodAnalysisDialogBase.java

Issue #101 fix.

---

build.xml

Fixed the file copying elements in Ant build file.

#112: fixed javadoc file copy instances

---

src/org/aavso/tools/vstar/ui/dialog/prefs/ChartPropertiesSelectionPane.java
src/org/aavso/tools/vstar/ui/dialog/prefs/PreferencesDialog.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java
src/org/aavso/tools/vstar/ui/pane/plot/AbstractObservationPlotPane.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
src/org/aavso/tools/vstar/util/prefs/ChartPropertiesPrefs.java

"Chart Properties" tab in Preferences.

---

src/org/aavso/tools/vstar/ui/dialog/prefs/ChartPropertiesSelectionPane.java
src/org/aavso/tools/vstar/ui/dialog/prefs/NumericPrecisionSelectionPane.java
src/org/aavso/tools/vstar/ui/dialog/prefs/SeriesColorSelectionPane.java
src/org/aavso/tools/vstar/ui/dialog/prefs/SeriesSizeSelectionPane.java
src/org/aavso/tools/vstar/ui/pane/plot/AbstractObservationPlotPane.java
src/org/aavso/tools/vstar/util/prefs/NumericPrecisionPrefs.java

Issue #123 fix.

---

src/org/aavso/tools/vstar/ui/vela/VeLaDialog.java

VeLa dialog "no output" fix.

---

plugin/src/org/aavso/tools/vstar/external/plugin/KeplerFITSObservationSource.java

Check for flux > 0 added into KeplerFITSObservationSource (issue #148)

KeplerFITSObservationSource: check for flux > 0 added.

---

plugin/src/org/aavso/tools/vstar/external/plugin/AoVPeriodSearch.java

Issue #152 fixed: Infinity values replaced by NaN to prevent jfreechart 'java.lang.IllegalArgumentException: Must be finite' error.

Issue #152 fix

---

src/org/aavso/tools/vstar/ui/VStar.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
test/org/aavso/tools/vstar/plugin/PluginManagerTest.java

Issue #162 fix: force VeLa initialization before loading plug-ins

---

plugin/src/org/aavso/tools/vstar/external/plugin/DescStatsBySeries.java

The plugin now shows _visible_ series. In addition to the 'physical' series it shows synthetic (mean, filtered, etc.) and user-defined series (Issue #164).
The plugin got a new look.

Issue 164 DescsStatBySeries plugin update

---

plugin/src/org/aavso/tools/vstar/external/plugin/HJDConverter.java

HJDConverter updates UI (including deletion of active phase plot) only if it was not canceled.

---

src/org/aavso/tools/vstar/ui/mediator/Mediator.java

Series info from active analysisType in Mediator.invokeTool(...)

---

plugin/src/org/aavso/tools/vstar/external/plugin/DescStatsBySeries.java

MEAN series excluded if it is phase MEAN, calcMagMeanInRange throws an exception.

---

plugin/src/org/aavso/tools/vstar/external/plugin/MagnitudeBaselineShifter.java

#184: removed odd unnecessary Math.abs call

---

build-win-installer.xml
plugin/build.xml
plugin/src/org/aavso/tools/vstar/external/plugin/HJDConverter.java
plugin/src/org/aavso/tools/vstar/external/plugin/JulianDateObservationsFilter.java
src/org/aavso/tools/vstar/data/ValidObservation.java
src/org/aavso/tools/vstar/input/AbstractObservationRetriever.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java
src/org/aavso/tools/vstar/ui/resources/ResourceAccessor.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java

Hi @dbenn ,
It seems I cannot add more at this time. So please review it...
Cheers,
Max

Issue 185 hj dconverted converts bjd

---

plugin/src/org/aavso/tools/vstar/external/plugin/VSXquery.java

See issue #205
Added a field with Sexagesimal coordinates

Sexagesimal coordinates in VSXquery.

---

src/org/aavso/tools/vstar/ui/dialog/MultiEntryComponentDialog.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java

This fix also addresses issues #75 and #74
Also, an error dialog was introduced in MultiEntryComponentDialog for better diagnostic of input errors: it shows the name of the input field with the error and reminds the user of the constraints.

Issue #210 fix: requestRA/requestDec min/max input boundaries.

---

test/org/aavso/tools/vstar/vela/VeLaTest.java

Hi @mpyat2, please review the unit test additions. If there are any further issues after this is merged, I'll create a new branch.

Issue 227 poly model function error

---

src/org/aavso/tools/vstar/ui/dialog/PlotControlDialog.java
src/org/aavso/tools/vstar/ui/mediator/DocumentManager.java
src/org/aavso/tools/vstar/ui/pane/plot/ObservationAndMeanPlotPane.java

Thanks Max, when you get the chance.

#244: persisting Show settings in Plot Control Dialog across dataset loads

---

plugin/src/org/aavso/tools/vstar/external/plugin/BMinusVObservationSource.java
src/org/aavso/tools/vstar/data/ValidObservation.java

Well, this turned out to be bigger than Ben Hur. The name is being set now for B-V observations. In addition, the mag uncertainty is now being computed and set. Finally, a test method was added for the plugin, something I plan to do when the opportunity arises because the test coverage for plugins is low.
@mpyat2, if you are happy to review this, that would be great.

246 B-V observation source plugin creates observations with no names

---

src/org/aavso/tools/vstar/data/CommentCodes.java
src/org/aavso/tools/vstar/data/Magnitude.java
src/org/aavso/tools/vstar/data/ValidObservation.java
src/org/aavso/tools/vstar/ui/dialog/SeriesTypeCreationDialog.java
src/org/aavso/tools/vstar/ui/mediator/message/FilteredObservationMessage.java
test/org/aavso/tools/vstar/data/ValidObservationTest.java

Hi @mpyat2, I have implemented a full `copy()` method, used it in `FilteredObservationMessage` and `SeriesTypeCreationDialog` and tested it with mag baseline shift so far. I've also added a `ValidObservation` unit test for `copy()` and mutability.
If you have a look at this, it would be appreciated.

#51: implemented full ValidObservation copy

---

build.xml
src/org/aavso/tools/vstar/ui/dialog/AboutBox.java
src/org/aavso/tools/vstar/ui/resources/ResourceAccessor.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java.template

Hi @dbenn , I've added a timestamp along with the existing git revision number: the timestamp is the build time in "yyyy-MM-dd HH:mm" format. The time is local, it would be better to have UTC yet I have not found if it is possible using the standard ant tstamp task.

Build time in AboutBox

---

src/org/aavso/tools/vstar/ui/VStar.java

This option disables the setting of the 'native' to the system look and feel.
Linux:
./VStar.sh --default-look-and-feel
Windows:
VStar.exe --default-look-and-feel

--default-look-and-feel command line option

---

src/org/aavso/tools/vstar/util/model/PeriodAnalysisDerivedMultiPeriodicModel.java
test/org/aavso/tools/vstar/util/MiraDataSmall.java
test/org/aavso/tools/vstar/util/period/dcdft/DcDftDerivedFourierModelErrorTest.java

Okay, I've implemented FWHM @mpyat2 if you would not mind reviewing it.
Uncertainty results appear in the models dialog along with std errors now.
I have not yet added a button to show FWHM independent of model creation even though it is not tied to that, because it seems most useful in combination with the standard error of the frequency which is what the original context was.

256 dcdft fwhm as a measure of period error

---

src/org/aavso/tools/vstar/util/model/PeriodAnalysisDerivedMultiPeriodicModel.java

Thanks @mpyat2 in advance for your review.

278 broken fourier model cannot find specified frequency in dcdft result error

---

src/org/aavso/tools/vstar/data/SeriesType.java
src/org/aavso/tools/vstar/ui/VStar.java
src/org/aavso/tools/vstar/util/locale/LocaleProps.java

Error reading/saving some preferences in WebStart mode fix.

---

src/org/aavso/tools/vstar/util/date/MeeusDateUtil.java
test/org/aavso/tools/vstar/util/date/DateUtilTestBase.java

Fixes obs list column ordering problem, and is well, ISO 8601!

#288: changed date string representation to ISO-8601

---

src/org/aavso/tools/vstar/ui/dialog/model/HarmonicPeriodPane.java
src/org/aavso/tools/vstar/ui/resources/ResourceAccessor.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
src/org/aavso/tools/vstar/util/model/PeriodAnalysisDerivedMultiPeriodicModel.java
test/org/aavso/tools/vstar/util/period/dcdft/DcDftDerivedFourierModelErrorTest.java

As per comments in #294 @mpyat2, I think these changes are now all that's needed. Please review when you have the chance.

294 fwhm dialog fix

---

src/org/aavso/tools/vstar/data/filter/AbstractObservationFieldMatcher.java
src/org/aavso/tools/vstar/data/filter/ObservationFilter.java
src/org/aavso/tools/vstar/data/filter/SeriesTypeFieldMatcher.java
src/org/aavso/tools/vstar/ui/dialog/filter/ObservationFilterDialog.java
src/org/aavso/tools/vstar/ui/dialog/filter/ObservationFilterPane.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java
src/org/aavso/tools/vstar/ui/model/list/ValidObservationTableModel.java
src/org/aavso/tools/vstar/ui/model/plot/ObservationPlotModel.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java
src/org/aavso/tools/vstar/util/ObservationInserter.java
src/org/aavso/tools/vstar/vela/VeLaValidObservationEnvironment.java

Hi @mpyat2. This PR covers changes that affect #243 and #253. See also comments in those issues. When you have the chance to review. Thanks.

253 some filter mechanisms ignore user defined series

---

src/org/aavso/tools/vstar/ui/model/plot/ObservationAndMeanPlotModel.java

Hi @mpyat2. I've committed a simple fix for this. Let me know what you think if you are able to.

#310: checking that selected series has observations

---

plugin/src/org/aavso/tools/vstar/external/plugin/GAIADR2XformObSource.java

332 the gaia dr2 photometry plugin currently does not work because of web service unavailability

---

plugin/build.xml
plugin/src/org/aavso/tools/vstar/external/lib/GaiaObSourceBase.java
plugin/src/org/aavso/tools/vstar/external/plugin/GAIADR2XformFileObSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/GAIADR2XformObSource.java
src/org/aavso/tools/vstar/ui/dialog/plugin/manager/PluginManager.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java

Hi @dbenn ,
Here are severely reworked GAIADR2XformObSource (retrieving Gaia data from the Internet) and the new GAIADR2XformFileObSource, which reads from a local file. Both extend the base class GaiaObSourceBase, which is moved to a separate shared jar, placed in vstar_plugin_libs. PluginManager refused to work with them (it could not create an instance of the Gaia class because it did not retrieve the shared jar from a remote location). So I fixed the PluginManager too.
I also made some additional PluginManager fixes and refactoring. Although it was not directly related to the Gaia plug-ins, as far as the PluginManager needed to be fixed anyway, I decided to make more fixes. One important fix was the new areURLReferentsEqual() method. The old one ALWAYS gave FALSE. The new one, I hope, …

Issue 337 gaia plug in enhancement

---

plugin/build.xml
plugin/src/org/aavso/tools/vstar/external/lib/ZTFObSourceBase.java
plugin/src/org/aavso/tools/vstar/external/plugin/GAIADR2XformObSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/ZTFFileObSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/ZTFObSource.java

I added a new ZTF file-based plug-in. It shares code with the ZTF-internet-source plug-in (ZTFObSource) so the new shared lib was created also.
The new "Copy ZTF URL to clipboard" button was added to the ZTF Photometry dialog (and the similar one to the GAIADR2XformObSource)

Issue 351 ztf file plugin

---

build.xml
test/org/aavso/tools/vstar/input/database/VSXWebServiceStarInfoSourceTest.java

@mpyat2 You probably don't need to review this given it's Mac specific.

#374: updates to build.xml Ant target to fix problem with code signing

---

src/org/aavso/tools/vstar/ui/dialog/DateToJdDialog.java
src/org/aavso/tools/vstar/ui/dialog/StarSelectorDialog.java

StarSelectorDialog: an ability to enter minimum/maximum JD as calendar dates. Min/Max JD tooltip update improved. See #384

Added an ability to enter minimum/maximum JD as calendar dates.

---

ReadMe.md
src/org/aavso/tools/vstar/ui/dialog/period/wwz/WWZPlotPane.java

Please check this works for you after the fix and review code @mpyat2

#390: added check for zero (or close to) min/max range in WWZ plot pane

---

src/org/aavso/tools/vstar/ui/mediator/DocumentManager.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java

Hi @mpyat2, let me know if you have questions

#395: changed to capture checkbox state for both analysis types

---

plugin/src/org/aavso/tools/vstar/external/plugin/VSXquery.java

VXSQuery extensions

---

plugin/src/org/aavso/tools/vstar/external/plugin/VeLaModelCreator.java
src/org/aavso/tools/vstar/vela/VeLaValidObservationEnvironment.java
test/org/aavso/tools/vstar/vela/VeLaTest.java

Hi @mpyat2. Please review the fix.

429 error while creating vela model

---

plugin/src/org/aavso/tools/vstar/external/plugin/AAVSOUploadFileFormatObservationSource.java

Hi @mpyat2 I've added DSLR OBSTYPE as per comment in #423

#423: added DSLR OBSTYPE

---

src/org/aavso/tools/vstar/ui/mediator/DocumentManager.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java

431 plot control checkboxes sometimes go out of sync

---

src/org/aavso/tools/vstar/ui/vela/VeLaDialog.java

Hi @mpyat2. A small fix but nice to sort out.

#394: fixed error message resulting from no result for functions that return no values

---

script/VeLa/fact.vl
script/VeLa/piecewise_linear_model.vl
script/VeLa/velarepl.vl
src/org/aavso/tools/vstar/vela/AST.java
src/org/aavso/tools/vstar/vela/ExpressionVisitor.java
src/org/aavso/tools/vstar/vela/Operation.java
src/org/aavso/tools/vstar/vela/VeLa.g4
src/org/aavso/tools/vstar/vela/VeLaInterpreter.java
test/org/aavso/tools/vstar/vela/VeLaTest.java

Hi @mpyat2. I hope you like the idea of this. :)

357 alternative vela block and selection syntax

---

script/VeLa/Y/README.md
script/VeLa/Y/Y-step1.vela
script/VeLa/Y/Y-step2.vela
script/VeLa/Y/Y-step3.vela
script/VeLa/Y/Y-step4.vela
script/VeLa/Y/Y.vela
src/org/aavso/tools/vstar/vela/ExpressionVisitor.java
src/org/aavso/tools/vstar/vela/FunctionExecutor.java
src/org/aavso/tools/vstar/vela/Operation.java
src/org/aavso/tools/vstar/vela/VeLa.g4
src/org/aavso/tools/vstar/vela/VeLaInterpreter.java
test/org/aavso/tools/vstar/vela/VeLaTest.java

This is a bit oscure @mpyat2 so let me know if you have questions. It was really just a bug in function application in the presence of HOFs. The Y combinator stress tested it.

105 may need apply in vela

---

plugin/src/org/aavso/tools/vstar/external/lib/GaiaObSourceBase.java
plugin/src/org/aavso/tools/vstar/external/plugin/GAIADR2XformFileObSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/GAIADR2XformObSource.java

Hi @dbenn 
I fixed the Gaia DR2/DR3 plugin according to the new Gaia DR3 format.

A new Gaia DR3 format (Jan 2025+) has been implemented.

---

plugin/src/org/aavso/tools/vstar/external/plugin/VSXquery.java
src/org/aavso/tools/vstar/auth/AAVSOPostUserPassXMLAuthenticationSource.java
src/org/aavso/tools/vstar/auth/VSXWebServiceMemberInfo.java
src/org/aavso/tools/vstar/input/database/VSXWebServiceStarInfoSource.java
src/org/aavso/tools/vstar/plugin/ob/src/impl/AIDWebServiceObservationSourcePluginBase.java
src/org/aavso/tools/vstar/ui/resources/ResourceAccessor.java
src/org/aavso/tools/vstar/util/discrepant/VSXWebServiceZapperLogger.java

Changed API URL in a number of classes and created a common base URL string value.
Please review.

458 jan 2025 vsx and aavso url changes

---

src/org/aavso/tools/vstar/ui/dialog/prefs/ChartPropertiesSelectionPane.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java
src/org/aavso/tools/vstar/ui/pane/plot/AbstractObservationPlotPane.java
src/org/aavso/tools/vstar/util/prefs/ChartPropertiesPrefs.java

Hi David, 
I've added the customization of chart fonts (see #480). I wanted to make the chart more 'sexy' for publications; well, the quality of PNGs is still not perfect, but could become slightly better after the manual font tuning (IMHO).
What do you think?
(I probably do additional checks and tunings)

Customizable chart fonts

---

plugin/src/org/aavso/tools/vstar/external/lib/PiecewiseLinearModel.java
plugin/src/org/aavso/tools/vstar/external/plugin/ApacheCommonsLoessFitter.java
plugin/src/org/aavso/tools/vstar/external/plugin/VeLaModelCreator.java
src/org/aavso/tools/vstar/ui/task/ModellingTask.java
src/org/aavso/tools/vstar/ui/vela/VeLaDialog.java
src/org/aavso/tools/vstar/vela/UserDefinedFunctionExecutor.java
src/org/aavso/tools/vstar/vela/VeLaEnvironment.java
src/org/aavso/tools/vstar/vela/VeLaInterpreter.java
src/org/aavso/tools/vstar/vela/VeLaScope.java
src/org/aavso/tools/vstar/vela/VeLaValidObservationEnvironment.java
test/org/aavso/tools/vstar/vela/VeLaTest.java

@mpyat2 I have changed the VeLa function that's generated for a loess model in the Models dialog.
According to my reading of https://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/org/apache/commons/math3/analysis/polynomials/PolynomialSplineFunction.html, the implementation is correct, but does not behave as expected. Please see if you can spot a problem.

145 apachecommonsloessfitter generates incorrect textual representations for its model

---

src/org/aavso/tools/vstar/ui/dialog/TextDialog.java
src/org/aavso/tools/vstar/ui/vela/VeLaDialog.java

Scrollbars were added to VeLa dialog's text fields

---

plugin/src/org/aavso/tools/vstar/external/plugin/DFTandSpectralWindow.java

Now the FtResult object is always recreated with the selected dataset as a parameter.

Error selecting the work dataset in DFTandSpectralWindow fix

---

plugin/src/org/aavso/tools/vstar/external/plugin/DFTandSpectralWindowTest.java
plugin/src/org/aavso/tools/vstar/external/plugin/KeplerFITSObservationSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/LightKurveFITSObservationSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/QLPFITSObservationSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/SuperWASPFITSObservationSource.java
src/org/aavso/tools/vstar/data/validation/UncertaintyValueValidator.java
src/org/aavso/tools/vstar/plugin/ObservationSourcePluginBase.java
src/org/aavso/tools/vstar/plugin/PluginComponentFactory.java
src/org/aavso/tools/vstar/ui/dialog/AdditiveLoadFileOrUrlChooser.java
src/org/aavso/tools/vstar/ui/dialog/TextDialog.java
src/org/aavso/tools/vstar/ui/task/NewStarFromObSourcePluginTask.java

@mpyat2 This is an idea I had a few days ago and thought it would be a nice simple feature that's useful across many text obs sources.
Try clicking `Request Observation Text` button on file chooser for Download and Simple formats and entering this text into the resulting text dialog:
~~~
50040.5103	11.1619
50048.7349	11.2937
50059.4429	11.3571
50069.6663	11.6182
50078.0090	11.5417
50089.7605	11.4917
50098.0664	11.4944
50109.4731	11.2417
50121.0239	11.0556
50131.1040	11.0667
50139.8784	10.6273
50150.3179	10.2450
50159.2695	9.9667
50170.2480	9.1909
50179.4995	8.5750
50188.5771	8.3400
50197.8154	8.1444
50210.5557	8.1600
50223.5605	7.9750
50230.5376	8.1333
~~~

#500: added Request Observation Text button on additive load file chooser
