src/org/aavso/tools/vstar/ui/dialog/AbstractOkCancelDialog.java

AbstractOkCancelDialog: setDefaultCloseOperation(DISPOSE_ON_CLOSE) added to dialog's constructor to prevent possible memory leak while closing inherited dialogs by window menu button ([x] under Windows)

Possible memory leak from AbstractOkCancelDialog

---

src/org/aavso/tools/vstar/ui/MenuBar.java
src/org/aavso/tools/vstar/ui/dialog/plugin/manager/PluginManagementDialog.java
src/org/aavso/tools/vstar/ui/dialog/plugin/manager/PluginManager.java
src/org/aavso/tools/vstar/ui/dialog/prefs/PluginSettingsPane.java
src/org/aavso/tools/vstar/ui/resources/PluginLoader.java

Issue #7: plug-ins cannot be deleted under Windows.
The fix attempts to resolve the issue: ClassLoader-s and streams are closed while plugin management.
Also, a small piece of code has been added to MenuBar.java to prevent starting PluginManagementDialog twice (currently this is possible even if PluginManagementDialog were modal: there is enough time to click the menu many times while initialization of PluginManagementDialog).
After any plugin-management-related operation, a user prompted to restart VStar.

Attempt to fix plugin deletion error under Windows.

---

plugin/src/org/aavso/tools/vstar/external/plugin/DescStatsBySeries.java

I've added "magnitude median" to "Descriptive statistics by series" plugin.
Sometimes, while estimating the base magnitude level of the different datasets, the median works better than the mean, especially for eclipsing stars.

"Magnitude median" added.

---

plugin/src/org/aavso/tools/vstar/external/plugin/SuperWASPFITSObservationSource.java

There are two versions of data in SuperWASP FITS file: FLUX2 and TAMFLUX2 (https://exoplanetarchive.ipac.caltech.edu/docs/SuperWASPProcessing.html). The situation is similar to TESS/Kepler: the first set is ‘raw’, the second one is ‘corrected’ (TAMFLUX2 = ‘SYSREM corrected fluxes’).
Existing SuperWASP plugin reads FLUX2 (‘raw’). The quality of the ‘raw’ data is too bad. On the other hand, magnitudes calculated from TAMFLUX2 (corrected fluxes) are the same as in CSV files that can be downloaded along with FITS from the SuperWASP portal (https://wasp.cerit-sc.cz/form).
I’ve been using SuperWASP CSV data for a long time and noticed quite long ago that they differ from those derived by VStar plugin from FITS. However, only now I investigated SuperWASP FITS and found the source of the …

SuperWASP TAMFLUX2 support

---

src/org/aavso/tools/vstar/ui/dialog/DoubleField.java

DoubleField.setValue() is locale-specific now and is consistent with getValue()

Issue 70 double field set value issue

---

src/org/aavso/tools/vstar/ui/mediator/Mediator.java

In both cases, max was null and min was 0 or previous value.
@clkotnik, @mdadighat, @mdadighat: if anyone has the chance to review this change, that'd be great. Thanks.

#67: fixed dec min/max in dialog field; also fixed RA min/max

---

src/org/aavso/tools/vstar/ui/VStar.java

If VStar started under Windows, TextArea font replaced by TextField font in main().
See the result below. Now TextArea font is readable.

Fixed TextArea ultra-small font issue

---

src/org/aavso/tools/vstar/vela/VeLaEnvironment.java
src/org/aavso/tools/vstar/vela/VeLaInterpreter.java
test/org/aavso/tools/vstar/vela/VeLaTest.java

Fixed by converting new value's type to the type of the existing binding or throwing an exception; added comments and deprecated a function.

#58: VeLa variables may undesirably change type

---

plugin/src/org/aavso/tools/vstar/external/plugin/ApacheCommonsLoessFitter.java
src/org/aavso/tools/vstar/plugin/model/impl/ApacheCommonsPolynomialFitCreatorPlugin.java
src/org/aavso/tools/vstar/util/locale/LocaleProps.java
src/org/aavso/tools/vstar/util/model/PeriodAnalysisDerivedMultiPeriodicModel.java
src/org/aavso/tools/vstar/util/model/PeriodFitParameters.java
src/org/aavso/tools/vstar/util/prefs/NumericPrecisionPrefs.java

Hi David @dbenn,
This branch addresses issues #14 and #92.
The following files/classes have been changed:
ApacheCommonsLoessFitter.java
ApacheCommonsPolynomialFitCreatorPlugin.java
PeriodAnalysisDerivedMultiPeriodicModel.java
PeriodFitParameters.java
toRString(): locale-independent formatting (using ENGLISH locale)
toExcelString(): formula separator should be locale-dependent. If ',' is a decimal separator, the Excel formula separator is changed to ';'.
ApacheCommonsLoessFitter, ApacheCommonsPolynomialFitCreatorPlugin: polynomial coefficients are formatted now using scientific notation (with configured precision: in this case it is a total number of significant digits) via new functions NumericPrecisionPrefs.formatPolyCoef/formatPolyCoefLocaleIndependent. This is because the coefficients …

Issue 14 rcomma non en locales

---

src/org/aavso/tools/vstar/data/ValidationType.java
src/org/aavso/tools/vstar/data/validation/AAVSODownloadFormatValidator.java
src/org/aavso/tools/vstar/data/validation/CommonTextFormatValidator.java
src/org/aavso/tools/vstar/data/validation/SimpleTextFormatValidator.java
src/org/aavso/tools/vstar/data/validation/ValflagValidator.java
test/org/aavso/tools/vstar/input/text/TextFormatObservationReaderTest.java

This gives backward compatibilty with simple format (that permitted the D valflag) and unifies both formats with respect to valflags.

#140: using common valflags for simple and AAVSO download formats and added unvalidated valflag

---

plugin/src/org/aavso/tools/vstar/external/plugin/HJDConverter.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java

Issue #76 fix.
In HJDConverter: updateUI() method. It switches to raw plot and tries to delete phase plot if active (because phases cannot be updated in the current VStar version), refreshes the table pane, and raw plot. A new "dropPhasePlotAnalysis()" method added to Mediator.

Updating plot and table after HJD convert: Issue #76

---

plugin/src/org/aavso/tools/vstar/external/plugin/QLPFITSObservationSource.java

See issue #181.
Fix for invalid 'time fractional part' keyword name (TESS QLP FITS header)

TESS QLP FITS: BJDRE* keywords fixed (should be BJDREFI/BJDREFR)

---

plugin/src/org/aavso/tools/vstar/external/plugin/JDToDateTool.java
src/org/aavso/tools/vstar/ui/dialog/DoubleField.java
src/org/aavso/tools/vstar/ui/dialog/IntegerField.java

Hi @dbenn ,
I've made a completely new "JD to Calendar date" plug-in (see Issue #208).
It is bidirectional, one can convert from JD to Date/Time and vice versa.
I also patched DoubleField.java and IntegerField.java. There was a bug in both classes that could cause Null Pointer Exception: I replaced null assignment to the variable by the 'return null' statement to avoid comparison of null with a variable.
Also, I've added 'catch (VeLaParseError e)' and 'catch (VeLaEvalError e)' in IntegerField.getValue() like in DoubleField.getValue(). Those exceptions can be thrown by NumberParser.parseInteger().

Issue 208 extend jd to cal date plugin

---

plugin/src/org/aavso/tools/vstar/external/plugin/FourierModelCreator.java
src/org/aavso/tools/vstar/ui/dialog/model/HarmonicPeriodPane.java

Issue #215 fix: 
1) HarmonicPeriodPane: catching parseDouble() exceptions (like in DoubleField class; 
2) FourierModelCreator: handling all possible exceptions in getModel().
to-do: replace 'JTextField periodField' by DoubleFiled?

Issue #215 fix

---

src/org/aavso/tools/vstar/vela/ExpressionVisitor.java

@dbenn ,
I made additional changes in ExpressionVisitor.parseDouble to make it more error-proof. Please see the comments in the source code. Could you please make unit tests for it?
I also checked if the locale affects _output_ formats used for generating textual representations of models.
The exponential format used for polynomial models (NumericPrecisionPrefs.formatScientific()) utilizes String.format() method.
Interestingly that it always uses normal Latin E for exponent regardless of locale (even for Ukrainian uk_UA while DecimalFormat.format prints Cyrillic Е for the scientific formats like "#.########E0" (Java ver>8), fortunately, we never use it in VStar).
So model expressions in the "Model information" are correct independently on the Java version and locale (I hope so).

Issue 229 expressionvisitor parsedouble bug

---

src/org/aavso/tools/vstar/util/prefs/NumericPrecisionPrefs.java

Output DecimalFormatSymbols are now the same as input ones.
Besides DecimalFormat, NumericPrecisionPrefs uses String.format() for values with exponents (used in polynomial models). Interestingly that String.format() does not suffer from Java version-to-version incompatibility like DecimalFormat. Although this is an inconsistency within the Java libraries themselves.

NumericPrecisionPrefs output format compatible with ExpressionVisitor input one.

---

src/org/aavso/tools/vstar/ui/dialog/series/MultipleSeriesSelectionDialog.java

The derived series pane has been included. Note that an observation transformer can act upon multiple series at once. This makes more sense in the context of recent changes in which new and filtered series are copied in order to avoid side effects.

#49: including derived series pane

---

src/org/aavso/tools/vstar/data/ValidObservation.java

I have fixed the bug by quoting the comments field and escaping any double quotes in the field by preceding each with a double quote, as per the CSV spec.
I've tested that this works using the V405 Dra data set, by saving and reloading it, and also adding quotes inside a row of data to see if it loads and saving it again to ensure that escaped quotes are preserved.

#311: quoting comments field including escaping of quotesw

---

plugin/src/org/aavso/tools/vstar/external/plugin/KeplerFITSObservationSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/QLPFITSObservationSource.java

In response to #314: Kepler/TESS and QLP observation sources were updated: reference Kepler or TESS magnitude read from the header is stored and displayed in the new column ("Kepler magnitude" or "TESS magnitude" respectively); the "Quality" field was added to Kepler/TESS (the field already existed in the QLP plug-in).
So now the user may exclude any bad points, check for the median or mean using the "Descriptive statistics by series" plug-in, and shift the baseline with the "Magnitude baseline shifter" (one of the possible approaches).
I've attached a 
[TESS_Kepler_TESSQLP_examples.zip](https://github.com/AAVSO/VStar/files/10369054/TESS_Kepler_TESSQLP_examples.zip)
with samples.

Kepler/TESS and QLP observation sources were updated

---

plugin/src/org/aavso/tools/vstar/external/plugin/QLPFITSObservationSource.java

Fixed #321: "ob.addDetail("QUALITY", ...)": the first parameter must be in uppercase.

Filter on "quality" for QLP fixed

---

plugin/src/org/aavso/tools/vstar/external/plugin/ASASSNObservationSource.java

Fixed issue #289 (format of precompiled ASAS-SN light curves was chaged so the plug-in cannot load them). Also, the first parameter of the observation detail "CAMERA" was capitalized; the "record" field was made more consistent.

Fixed issue #289 (format of precompiled ASAS-SN light curves was changed)

---

plugin/build.xml

The current plugin `ant clean` does not work on Windows, when it tries to deleting `src/**/*.class`:
```
BUILD FAILED
c:\dev\VStar\plugin\build.xml:276: java.nio.file.InvalidPathException: Illegal char <*> at index 24: c:\dev\VStar\plugin\src\**\*.class
at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
...
```
This PR fixed it.
I wonder, however, whether deleting `src/**/*.class` is still needed. On my build, there is no `.class` generated in `src.` directory. Is it needed for, say, Eclipse build? Or is it some legacy logic that can be removed?

make plugin ant clean works on Windows

---

src/org/aavso/tools/vstar/plugin/filter/impl/VeLaObservationFilterDialog.java
src/org/aavso/tools/vstar/ui/model/list/AAVSOFormatRawDataColumnInfoSource.java
src/org/aavso/tools/vstar/ui/model/list/ArbitraryFormatPhasePlotColumnInfoSource.java
src/org/aavso/tools/vstar/ui/model/list/ArbitraryFormatRawDataColumnInfoSource.java
src/org/aavso/tools/vstar/ui/model/list/ITableColumnInfoSource.java
src/org/aavso/tools/vstar/ui/model/list/SimpleFormatRawDataColumnInfoSource.java
src/org/aavso/tools/vstar/vela/VeLaValidObservationEnvironment.java
test/org/aavso/tools/vstar/vela/VeLaTest.java

I've addressed this @orionlee. Essentially, the observation list column names are the source for VeLa filter columns, along with some additional aliases (e.g. jd, time, t, mag, magnitude) and some context sensitive names (*phase).
The VeLa filter drop-down menu of names reflects these.
@mpyat2: you may be interested to look at this.

324 provide means to know the valid names for columns used in vela filter

---

plugin/build.xml
plugin/src/org/aavso/tools/vstar/external/lib/TESSObservationRetrieverBase.java
plugin/src/org/aavso/tools/vstar/external/plugin/KeplerFITSObservationSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/LightKurveFITSObservationSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/QLPFITSObservationSource.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java

Issue #342: KEPLER/TESS, QLP, LightKurve plug-ins now derive their ObservationRetriever's from TESSObservationRetrieverBase. 
A new observation detail -- "Flux" -- was added.
FITS rows having bad flux/flux_error are now collected to the invalid observations list.

TESS-related plug-ins optimization

---

plugin/src/org/aavso/tools/vstar/external/plugin/VSXquery.java

A "starVSXname" variable local for the VSX dialog was introduced that solves the incorrect "Ephemeris" title problem (Issue #371).

VSX Query dialog: "Ephemeris" wrong title bug solved (#371)

---

src/org/aavso/tools/vstar/ui/dialog/plugin/manager/PluginManagementDialog.java
src/org/aavso/tools/vstar/ui/dialog/plugin/manager/PluginManager.java

Fixed areURLReferentsEqual; in the PluginManager dialog, an item is grayed if local and remote plug-ins differ or if the remote plug-in does not exist.

Fixed areURLReferentsEqual; PluginManager dialog tuning

---

src/org/aavso/tools/vstar/plugin/period/PeriodAnalysisDialogBase.java
src/org/aavso/tools/vstar/ui/dialog/model/HarmonicInfoDialog.java
src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysis2DChartPane.java
src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysis2DResultDialog.java
src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysisDataTablePane.java
src/org/aavso/tools/vstar/ui/dialog/period/PeriodAnalysisTopHitsTablePane.java
src/org/aavso/tools/vstar/ui/dialog/period/wwz/WWZDataTablePane.java
src/org/aavso/tools/vstar/ui/dialog/period/wwz/WWZPlotPane.java
src/org/aavso/tools/vstar/ui/dialog/period/wwz/WeightedWaveletZTransformResultDialog.java
src/org/aavso/tools/vstar/ui/mediator/Mediator.java
src/org/aavso/tools/vstar/ui/mediator/message/HarmonicSearchResultMessage.java
src/org/aavso/tools/vstar/ui/mediator/message/MessageBase.java

This addresses issues #381, #382, and at least partially #61 (IllegalArgumentException while selecting harmonics in HarmonicInfoDialog).

Period analysis dialog issues with messages

---

VStar.sh

It's a small change. Tested on Mac M2. Will check on Raspberry Pi. If you have a Linux machine, feel free to check there if you like @mpyat2.

#386: changed _64 to 64 in grep

---

plugin/src/org/aavso/tools/vstar/external/lib/TESSObservationRetrieverBase.java
plugin/src/org/aavso/tools/vstar/external/plugin/KeplerFITSObservationSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/LightKurveFITSObservationSource.java
plugin/src/org/aavso/tools/vstar/external/plugin/QLPFITSObservationSource.java
src/org/aavso/tools/vstar/plugin/ObservationSourcePluginBase.java
src/org/aavso/tools/vstar/plugin/PluginComponentFactory.java
src/org/aavso/tools/vstar/ui/MenuBar.java
src/org/aavso/tools/vstar/ui/dialog/AdditiveLoadFileOrUrlChooser.java
src/org/aavso/tools/vstar/ui/task/NewStarFromObSourcePluginTask.java

Hi @mpyat2, please see what I've written in the issue and let me know if you have questions.
I may add the multiple file feature to other plugins before we close this but for now it's just the infrastructure and TESS-common-code plugins. Indeed, given a Jan 31-ish release deadline due to Auth0 (more like Feb 1 or 2 I'd say), there may not be time for much more.

398 load multiple observation files in sequence

---

src/org/aavso/tools/vstar/plugin/ob/sink/impl/SimpleFormatObservationSinkPlugin.java
src/org/aavso/tools/vstar/ui/task/ModellingTask.java
src/org/aavso/tools/vstar/ui/task/ObsListFileSaveTask.java
src/org/aavso/tools/vstar/ui/task/PeriodAnalysisTask.java
src/org/aavso/tools/vstar/ui/task/PluginManagerOperationTask.java
src/org/aavso/tools/vstar/ui/task/UndoableActionTask.java

Hi @mpyat2. Have a look at the fix. I tested it by modifying the `SimpleFormatObservationSinkPlugin` to throw an exception. We take this same `MessageBox` approach in `NewStarFrom*` task code.

#407: catching exceptions in obs file save task

---

plugin/src/org/aavso/tools/vstar/external/plugin/GAIADR2XformObSource.java

Actually, it was not a bug: one of the parameters of the web query was changed.

Gaia service URL has been updated to make the plug-in work again

---

src/org/aavso/tools/vstar/data/ValidObservation.java

ValidObservation.toSimpleFormatString, toAAVSOFormatString: text fields are double-quoted if they contain the delimiter.

---

plugin/src/org/aavso/tools/vstar/external/plugin/FlexibleTextFileFormatObservationSink.java
src/org/aavso/tools/vstar/data/ValidObservation.java

FlexibleTextFileFormatObservationSink utilizes quoteForCSVifNeeded/quoteForCSV from ValidObservation

FlexibleTextFileFormatObservationSink utilizes quoteForCSVifNeeded/quoteForCSV from ValidObservation

---

src/org/aavso/tools/vstar/plugin/ObservationSourcePluginBase.java
src/org/aavso/tools/vstar/plugin/ob/src/impl/TextFormatObservationSourcePlugin.java

Hi @mpyat2
I'm taking the minimal approach here of propagating the exception (removed the `try`..`catch`, added `throw` clause), allowing it to be caught higher up so that it appears in an error dialog box. There are many things that could be done to improve this code, but that's another issue entirely.
A question is whether or not `ObservationReadError` and `IOException` should be unified, e.g. caught and rethrown as `ObservationReadError`? Happy to make that change although one argument against that is that different exceptions thrown give more information, so leaving as multiple exceptions also makes sense.
Let mew know what you think.

424: changed exception handling in text format obs reader

---

src/org/aavso/tools/vstar/vela/VeLaInterpreter.java
test/org/aavso/tools/vstar/vela/VeLaTest.java

Hi @mpyat2. Working through a few VeLa issues. This is one I've wanted to work on for awhile. Added a bunch of UTs including property based tests.
I would suggest hiding whitespace in the pull request view since code was reformatted a few times.

404 arithmetic operations over lists in vela

---

plugin/src/org/aavso/tools/vstar/external/plugin/VeLaObSource.java
src/org/aavso/tools/vstar/ui/resources/RevisionAccessor.java

VeLaObSource: code editor undo/redo; new "Check" button: check code and parameters before execution

---

src/org/aavso/tools/vstar/plugin/filter/impl/VeLaObservationFilterDialog.java
src/org/aavso/tools/vstar/ui/vela/VeLaDialog.java
src/org/aavso/tools/vstar/vela/Type.java
src/org/aavso/tools/vstar/vela/VeLa.g4
test/org/aavso/tools/vstar/vela/VeLaTest.java

Hi @mpyat2. I've added shortcuts for some types as per #532 including escape-based keyboard shortcuts to the VeLa dialog, e.g. type `\` (which won't display) followed by `l`, `p`, `r` or `z` to see the effect (the `\` is consumed so you won't see it). More such shortcuts may be added over time. I removed `\b` for Boolean for now because of some contention over what Unicode character could/should be used.

#532: added shortened/alt names for types

---

src/org/aavso/tools/vstar/data/SeriesType.java
src/org/aavso/tools/vstar/ui/dialog/series/AIDSeriesSelectionPane.java

Hi @mpyat2, please review this small change

#535: added Gaia G
